### ISSUE TITLE
Please update the example to the Angular Release 

### ISSUE THREAD

**Issue by squadwuschel** [thoughtram/angular-migration-app#1]
Hi,

could you please update the example to the current Angular Release, because the new ngModule is not in the example atm.

thx squadwuschel

**Comment by 0x-r4bbit** [comment]
Hi @squadwuschel right now we don't have spare cycles to update the repository. But we welcome your contribution to make this change happen, if you really care!

Are you willing to contributing here? We can help you then :)

**Comment by squadwuschel** [comment]
at the moment I am looking for a working example for the current Angular 2 version with ngUpgrade. When I find someting that works I will post it here.

**Comment by 0x-r4bbit** [comment]
I figured that! :)

Thought you might want to help out updating _this_ example.
